# Generated by Django 3.0.8 on 2021-11-20 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictureApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='shared_users',
            field=models.ManyToManyField(default=None, null=True, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
