# Generated by Django 3.2.9 on 2021-11-18 20:53

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('pictureApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
