# Generated by Django 3.2.9 on 2021-11-20 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictureApp', '0002_auto_20211120_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_albums',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='shared_users',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
