# Generated by Django 3.2.9 on 2021-11-19 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictureApp', '0002_auto_20211118_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='main_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
