# Generated by Django 3.2.9 on 2021-11-20 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictureApp', '0003_auto_20211119_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='shared_users',
            field=models.ManyToManyField(default=None, null=True, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='User_Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.TextField(unique=True)),
                ('albumDescription', models.CharField(max_length=240)),
                ('contents', models.ManyToManyField(related_name='contents', to='pictureApp.User_Post')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
