# Generated by Django 3.2.9 on 2021-11-20 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictureApp', '0004_auto_20211120_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_albums',
            name='albumDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_albums',
            name='album_name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='user_albums',
            name='contents',
            field=models.ManyToManyField(default=None, related_name='contents', to='pictureApp.User_Post'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='shared_users',
            field=models.ManyToManyField(default=None, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
